version: '3.7'
services:
  web:
    networks:
      - proxy
      - default
    environment:
      VIRTUAL_HOST: snoqualmie.itgis.innovateteam.com
      VIRTUAL_PORT: 80
      VIRTUAL_PROTO: http
      LETSENCRYPT_HOST: snoqualmie.itgis.innovateteam.com
      LETSENCRYPT_EMAIL: tbock@innovateteam.com
      NGINX_ROOT: /usr/share/nginx/html/innovate/SnoqualmieEN
    expose:
      - "80"

networks:
  proxy:
    name: nginx_proxy_default
