version: '3.7'
services:
  web:
    image: docker.itgis.innovateteam.com/snoqualmie_assert
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped
    command: >
      /bin/sh -c "envsubst '$$VIRTUAL_HOST,$$NGINX_ROOT' < /etc/nginx/conf.d/snoqualmie.template > /etc/nginx/conf.d/default.conf
      && nginx -g 'daemon off;'"
    labels:
      - "com.centurylinklabs.watchtower.scope=innovate"
