version: '3.7'
services:
  web:
    image: docker.itgis.innovateteam.com/snoqualmie
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped
    command: >
      /bin/sh -c "envsubst '$$VIRTUAL_HOST' < /etc/nginx/conf.d/snoqualmie.template > /etc/nginx/conf.d/default.conf
      && nginx -g 'daemon off;'"
