version: '3.7'
services:
  web:
    image: docker.itgis.innovateteam.com/snoqualmie
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VIRTUAL_HOST: snoqualmie.itgis.innovateteam.com
      VIRTUAL_PORT: 80
      VIRTUAL_PROTO: http
      LETSENCRYPT_HOST: snoqualmie.itgis.innovateteam.com
      LETSENCRYPT_EMAIL: tbock@innovateteam.com
    expose:
      - "80"
    volumes:
      - ./template.nginx:/etc/nginx/conf.d/snoqualmie.template
    networks:
      - proxy
      - default
    restart: unless-stopped
    command: >
      /bin/sh -c "envsubst '$$VIRTUAL_HOST' < /etc/nginx/conf.d/snoqualmie.template > /etc/nginx/conf.d/default.conf
      && nginx -g 'daemon off;'"
